import type { DataType, MenuType, ModuleType, UsersDataType } from "./users";

export const data: DataType[] = [
  {
    key: "1",
    account: "00W001",
    name: "00W001 - YFY JUPITER (HKG)",
  },
  {
    key: "2",
    account: "00Z001",
    name: "00Z001 - APACHE FOOTWEAR VIETNAM (VNM)",
  },
  {
    key: "3",
    account: "1B9001",
    name: "1B9001 - PT GLOSTAR INDONESIA 1 (PGD IDN)",
  },
  {
    key: "4",
    account: "1BM001",
    name: "1BM001 - PT GLOSTAR INDONESIA 2 (PGS IDN)",
  },
  {
    key: "5",
    account: "1BM002",
    name: "1BM001 - PT GLOSTAR INDONESIA 2 (PGS IDN)",
  },
];

export const initialModuleData: ModuleType[] = [
  {
    key: "1",
    nameEn: "CI",
    nameVn: "CI",
    nameCn: "CI",
    status: "Active",
  },
  {
    key: "2",
    nameEn: "ESG",
    nameVn: "ESG",
    nameCn: "ESG",
    status: "Active",
  },
  {
    key: "3",
    nameEn: "GENERAL",
    nameVn: "GENERAL",
    nameCn: "GENERAL",
    status: "Active",
  },
  {
    key: "4",
    nameEn: "IT",
    nameVn: "IT",
    nameCn: "IT",
    status: "Active",
  },
  {
    key: "5",
    nameEn: "PLANNING",
    nameVn: "PLANNING",
    nameCn: "PLANNING",
    status: "Active",
  },
];

export const initialMenuData: MenuType[] = [
  {
    key: "1",
    module: "GENERAL",
    nameEn: "COLORS",
    nameVn: "COLORS",
    nameCn: "COLORS",
    status: "Active",
  },
  {
    key: "2",
    module: "ESG",
    nameEn: "MATERIALS",
    nameVn: "MATERIALS",
    nameCn: "MATERIALS",
    status: "Active",
  },
  {
    key: "3",
    module: "GENERAL",
    nameEn: "MATERIAL TEST REPORT",
    nameVn: "MATERIAL TEST REPORT",
    nameCn: "MATERIAL TEST REPORT",
    status: "Inactive",
  },
];

export const initialUsersData: UsersDataType[] = [
  {
    key: "1",
    userAccount: "1VW001",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW002",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW003",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW004",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW005",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW006",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW007",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW008",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW009",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW010",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW011",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW012",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW013",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW014",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW015",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW016",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW017",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW018",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW019",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW020",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW021",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW022",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW001",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW023",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW024",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW025",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW026",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW027",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW028",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW029",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW030",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW031",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW0032",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW033",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW034",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW035",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW036",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW037",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW038",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW039",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW040",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW041",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW042",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW043",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW044",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW045",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW046",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW047",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW048",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW049",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW050",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW051",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW052",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW053",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW054",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW055",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW056",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW057",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW058",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW059",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW060",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW061",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW062",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW063",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW064",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW065",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW066",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW067",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW068",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW069",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW070",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW071",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW072",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW073",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW074",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW075",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW076",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW077",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW078",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW079",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW080",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW081",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW082",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW083",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW084",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW085",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW086",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW087",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW088",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW089",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW090",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW091",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW092",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW093",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW094",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW095",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW096",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW097",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW098",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW099",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW100",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW101",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
];
