import type { LastLibraryDataType } from "./lastLibrary";
import type { DataType, MenuType, ModuleType } from "./users";

export const data: DataType[] = [
  {
    key: "1",
    account: "00W001",
    name: "00W001 - YFY JUPITER (HKG)",
  },
  {
    key: "2",
    account: "00Z001",
    name: "00Z001 - APACHE FOOTWEAR VIETNAM (VNM)",
  },
  {
    key: "3",
    account: "1B9001",
    name: "1B9001 - PT GLOSTAR INDONESIA 1 (PGD IDN)",
  },
  {
    key: "4",
    account: "1BM001",
    name: "1BM001 - PT GLOSTAR INDONESIA 2 (PGS IDN)",
  },
  {
    key: "5",
    account: "1BM002",
    name: "1BM001 - PT GLOSTAR INDONESIA 2 (PGS IDN)",
  },
];

export const initialModuleData: ModuleType[] = [
  {
    key: "1",
    nameEn: "CI",
    nameVn: "CI",
    nameCn: "CI",
    status: "Active",
  },
  {
    key: "2",
    nameEn: "ESG",
    nameVn: "ESG",
    nameCn: "ESG",
    status: "Active",
  },
  {
    key: "3",
    nameEn: "GENERAL",
    nameVn: "GENERAL",
    nameCn: "GENERAL",
    status: "Active",
  },
  {
    key: "4",
    nameEn: "IT",
    nameVn: "IT",
    nameCn: "IT",
    status: "Active",
  },
  {
    key: "5",
    nameEn: "PLANNING",
    nameVn: "PLANNING",
    nameCn: "PLANNING",
    status: "Active",
  },
];

export const initialMenuData: MenuType[] = [
  {
    key: "1",
    module: "GENERAL",
    nameEn: "COLORS",
    nameVn: "COLORS",
    nameCn: "COLORS",
    status: "Active",
  },
  {
    key: "2",
    module: "ESG",
    nameEn: "MATERIALS",
    nameVn: "MATERIALS",
    nameCn: "MATERIALS",
    status: "Active",
  },
  {
    key: "3",
    module: "GENERAL",
    nameEn: "MATERIAL TEST REPORT",
    nameVn: "MATERIAL TEST REPORT",
    nameCn: "MATERIAL TEST REPORT",
    status: "Inactive",
  },
];

export const initialLastLibraryData: LastLibraryDataType[] = [
  {
    key: 1,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OOQ10",
    Article_Number_A: "JQ9147",
    Model_Name_Short_M: "NIZZA PLATFORM W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "12/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Jane.Lin@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "China_Mega_Moments",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 2,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OOQ10",
    Article_Number_A: "JQ9148",
    Model_Name_Short_M: "NIZZA PLATFORM W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "11/22/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Jane.Lin@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,China_Mega_Moments",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 3,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OOQ10",
    Article_Number_A: "JQ9149",
    Model_Name_Short_M: "NIZZA PLATFORM W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "11/22/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Jane.Lin@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,China_Mega_Moments",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 4,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OOQ10",
    Article_Number_A: "JQ9150",
    Model_Name_Short_M: "NIZZA PLATFORM W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "11/22/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Jane.Lin@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,China_Mega_Moments",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 5,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "NRB60",
    Article_Number_A: "JR8231",
    Model_Name_Short_M: "CRAZY 2",
    Sports_Category_M: "BASKETBALL",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "02/16/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "08/29/2024",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Eckart, Allan",
    Senior_Developer_A: "Brent.Allen@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "08/22/2024",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_loanvo@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/18/2025 10:29 AM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "PRE SELL,SMS",
    HQ_Render_Status_Timestamp_A: "02/07/2025 10:40 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "09/04/2024 06:36 AM GMT+07:00",
    Feasibility_Checked_Date_A: "07/18/2024",
    Image_Confidential_A: "No",
    Last_M: "51002",
  },
  {
    key: 6,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OPE07",
    Article_Number_A: "JS0864",
    Model_Name_Short_M: "adizero Cybersonic 2 W GC",
    Sports_Category_M: "TENNIS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "02/17/2025",
    Marketing_Department_A: "BU TENNIS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Kambhampati, Sushanth",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "",
    Image_Confidential_A: "No",
    Last_M: "32013",
  },
  {
    key: 7,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONF66",
    Article_Number_A: "JS2571",
    Model_Name_Short_M: "BARREDA",
    Sports_Category_M: "SPORTSWEAR",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV ",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "08/26/2024",
    Marketing_Department_A: "BU CORE FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/11/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "haithanh.trinh@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/04/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_trungngu@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "12/27/2024 10:45 AM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "12/26/2024 05:47 PM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "11/05/2024 06:38 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/29/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 8,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "BAW72",
    Article_Number_A: "B22705",
    Model_Name_Short_M: "3MC",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "05/06/2024",
    Marketing_Department_A: "BU ACTION SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "winny.wei@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 9,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "BAW75",
    Article_Number_A: "B22716",
    Model_Name_Short_M: "CAMPUS ADV",
    Sports_Category_M: "SKATEBOARDING",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "05/07/2024",
    Marketing_Department_A: "BU ACTION SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Scott, Stacy",
    Senior_Developer_A: "winny.wei@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41002",
  },
  {
    key: 10,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "BBB86",
    Article_Number_A: "B41645",
    Model_Name_Short_M: "GAZELLE",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/24/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Lilly.Cocks@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,CR2change,EG",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 11,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "BSZ08",
    Article_Number_A: "B75806",
    Model_Name_Short_M: "SAMBA OG",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "Service Model",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zeng, Sudan",
    Senior_Developer_A: "marco.dittrich@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A:
      "digital_creation_E2E,digital_creation_3D_service_model,BC_commercial",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 12,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "BSZ08",
    Article_Number_A: "B75807",
    Model_Name_Short_M: "SAMBA OG",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "Service Model",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zeng, Sudan",
    Senior_Developer_A: "marco.dittrich@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,digital_creation_3D_service_model",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 13,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "IAZ12",
    Article_Number_A: "BB5476",
    Model_Name_Short_M: "GAZELLE",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zeng, Sudan",
    Senior_Developer_A: "Lilly.Cocks@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,CR2change,EG",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 14,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "IAZ12",
    Article_Number_A: "BB5478",
    Model_Name_Short_M: "GAZELLE",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zeng, Sudan",
    Senior_Developer_A: "Lilly.Cocks@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,EG",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 15,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "IAZ12",
    Article_Number_A: "BB5480",
    Model_Name_Short_M: "GAZELLE",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zeng, Sudan",
    Senior_Developer_A: "Lilly.Cocks@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,3_STRIPES_TEE_FRANCHISE",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 16,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "EBF75",
    Article_Number_A: "EE5599",
    Model_Name_Short_M: "NIZZA RF",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "10/18/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Lilly.Cocks@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "11/28/2024",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 17,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "EBF75",
    Article_Number_A: "EF1883",
    Model_Name_Short_M: "NIZZA RF",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "10/18/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Lilly.Cocks@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "11/28/2024",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 18,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "KXU80",
    Article_Number_A: "FV5321",
    Model_Name_Short_M: "NIZZA PLATFORM W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "11/18/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Ruth.Venney@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "China_Mega_Moments",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "11/28/2024",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 19,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "KXU80",
    Article_Number_A: "FV5322",
    Model_Name_Short_M: "NIZZA PLATFORM W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "11/18/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Ruth.Venney@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 20,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "KZC10",
    Article_Number_A: "FX6563",
    Model_Name_Short_M: "GAZELLE ADV",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "05/07/2024",
    Marketing_Department_A: "BU ACTION SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Scott, Stacy",
    Senior_Developer_A: "winny.wei@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41036",
  },
  {
    key: 21,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LVK01",
    Article_Number_A: "GW2991",
    Model_Name_Short_M: "GameCourt 2 M",
    Sports_Category_M: "TENNIS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/17/2024",
    Marketing_Department_A: "BU TENNIS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "BC_commercial,bc_commercial_FW22",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "11/28/2024",
    Image_Confidential_A: "No",
    Last_M: "21001",
  },
  {
    key: 22,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LZM32",
    Article_Number_A: "GY0042",
    Model_Name_Short_M: "CAMPUS 00s W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "Service Model",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Ruth.Venney@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,digital_creation_3D_service_model",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "06/10/2024 07:07 PM GMT+07:00",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 23,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LKJ23",
    Article_Number_A: "GY6433",
    Model_Name_Short_M: "CAMPUS 00s",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Florian.Godenberg@adidas-group.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "bc_brand_calendar_FW22",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "06/13/2024 05:36 PM GMT+07:00",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 24,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LRW49",
    Article_Number_A: "GZ8477",
    Model_Name_Short_M: "SAMBA ADV",
    Sports_Category_M: "SKATEBOARDING",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "05/07/2024",
    Marketing_Department_A: "BU ACTION SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Gebhard, June",
    Senior_Developer_A: "winny.wei@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 25,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LZJ36",
    Article_Number_A: "H03471",
    Model_Name_Short_M: "CAMPUS 00s",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Florian.Godenberg@adidas-group.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 26,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LZJ36",
    Article_Number_A: "H03472",
    Model_Name_Short_M: "CAMPUS 00s",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Florian.Godenberg@adidas-group.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 27,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LZJ36",
    Article_Number_A: "H03474",
    Model_Name_Short_M: "CAMPUS 00s",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "04/05/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "SS25",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "Florian.Godenberg@adidas-group.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 28,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "LRW01",
    Article_Number_A: "H04930",
    Model_Name_Short_M: "TYSHAWN",
    Sports_Category_M: "SKATEBOARDING",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "05/07/2024",
    Marketing_Department_A: "BU ACTION SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "FW21",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Gebhard, June",
    Senior_Developer_A: "winny.wei@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_vuhai@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/22/2025 04:14 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "02/22/2025 12:01 PM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "07/19/2024",
    Image_Confidential_A: "No",
    Last_M: "41090",
  },
  {
    key: 29,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "MBT37",
    Article_Number_A: "HP2848",
    Model_Name_Short_M: "ZX 1K BOOST - SEAS. 2.0",
    Sports_Category_M: "SPORTSWEAR",
    Development_Type_A: "CARRY OVER",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "02/14/2025",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "FW24",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "TBA",
    Senior_Developer_A: "haithanh.trinh@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E,CR2change",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "",
    Expected_Milestone_A: "",
    HQ_Render_Status_Timestamp_A: "",
    HQ_Render_Status_A: "",
    Design_Sketch_Latest_Update_A: "",
    Feasibility_Checked_Date_A: "",
    Image_Confidential_A: "No",
    Last_M: "51011",
  },
  {
    key: 30,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "IAZ12",
    Article_Number_A: "HP3632",
    Model_Name_Short_M: "GAZELLE",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW COLOR",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "10/14/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/18/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Nguyen, David",
    Senior_Developer_A: "david.nguyen@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/11/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "11/05/2024 10:11 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "10/15/2024 03:39 PM GMT+07:00",
    Feasibility_Checked_Date_A: "11/02/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 31,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "IAZ12",
    Article_Number_A: "HP3633",
    Model_Name_Short_M: "GAZELLE",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW COLOR",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "DCE2E",
    Digital_Scope_Update_Date_A: "10/14/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/18/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Nguyen, David",
    Senior_Developer_A: "david.nguyen@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "digital_creation_E2E",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/11/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "11/05/2024 09:58 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "12/10/2024 11:39 PM GMT+07:00",
    Feasibility_Checked_Date_A: "11/02/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 32,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OMN91",
    Article_Number_A: "HP3653",
    Model_Name_Short_M: "CAMPUS 00s J",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/14/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/13/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Chu, Robin",
    Senior_Developer_A: "sven.liebold@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/06/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "doantrang.29898@lacty.com.vn",
    Published_Milestone_Timestamp_A: "05/13/2025 04:11 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "04/22/2025 09:52 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/10/2025 02:30 AM GMT+07:00",
    Feasibility_Checked_Date_A: "10/28/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 33,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OMN91",
    Article_Number_A: "HP3654",
    Model_Name_Short_M: "CAMPUS 00s J",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/14/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/13/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Chu, Robin",
    Senior_Developer_A: "sven.liebold@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/06/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "doantrang.29898@lacty.com.vn",
    Published_Milestone_Timestamp_A: "05/13/2025 04:11 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "04/22/2025 09:54 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/23/2025 04:29 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/28/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 34,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OPG56",
    Article_Number_A: "HP3659",
    Model_Name_Short_M: "GAZELLE INDOOR J",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "TAKE DOWN",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/14/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/06/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Chu, Robin",
    Senior_Developer_A: "sven.liebold@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/30/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "1ec3baf1-be42-42e5-b5f2-cde7f956b5aa",
    Published_Milestone_Timestamp_A: "04/10/2025 11:55 AM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "04/29/2025 04:22 PM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "10/21/2024 03:00 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/23/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 35,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "MCZ76",
    Article_Number_A: "HP3661",
    Model_Name_Short_M: "CAMPUS 00s J",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW COLOR",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "03/07/2025",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "03/28/2025",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Chu, Robin",
    Senior_Developer_A: "sven.liebold@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "03/21/2025",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "doantrang.29898@lacty.com.vn",
    Published_Milestone_Timestamp_A: "05/13/2025 04:11 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "10/28/2024 06:12 PM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "10/22/2024 03:43 AM GMT+07:00",
    Feasibility_Checked_Date_A: "10/28/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 36,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "NKT64",
    Article_Number_A: "HP3668",
    Model_Name_Short_M: "GAZELLE INDOOR",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW COLOR",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/21/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/20/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Penarrocha, Hector (formerly Penarrocha Fernandez)",
    Senior_Developer_A: "Penarrocha, Hector (formerly Penarrocha Fernandez)",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/13/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "11/07/2024 09:58 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "10/23/2024 08:03 PM GMT+07:00",
    Feasibility_Checked_Date_A: "11/07/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 37,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "NKT64",
    Article_Number_A: "HP3669",
    Model_Name_Short_M: "GAZELLE INDOOR",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW COLOR",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/21/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/20/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Penarrocha, Hector (formerly Penarrocha Fernandez)",
    Senior_Developer_A: "Penarrocha, Hector (formerly Penarrocha Fernandez)",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/13/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "11/07/2024 09:59 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "10/23/2024 08:03 PM GMT+07:00",
    Feasibility_Checked_Date_A: "11/07/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 38,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OMO00",
    Article_Number_A: "HP3693",
    Model_Name_Short_M: "CAMPUS 00s",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "04/22/2025",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "05/13/2025",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Geinzer, Carolin",
    Senior_Developer_A: "Penarrocha, Hector (formerly Penarrocha Fernandez)",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "05/06/2025",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "11/12/2024 12:13 PM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "03/08/2025 07:01 AM GMT+07:00",
    Feasibility_Checked_Date_A: "11/08/2024",
    Image_Confidential_A: "No",
    Last_M: "41103",
  },
  {
    key: 39,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL88",
    Article_Number_A: "HP7026",
    Model_Name_Short_M: "Crazyflight 6 W",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "NEW TOOLING",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 11:26 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:51 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 40,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL88",
    Article_Number_A: "HP7027",
    Model_Name_Short_M: "Crazyflight 6 W",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "NEW TOOLING",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 11:17 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:51 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 41,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL88",
    Article_Number_A: "HP7028",
    Model_Name_Short_M: "Crazyflight 6 W",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "NEW TOOLING",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 11:21 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:51 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 42,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL88",
    Article_Number_A: "HP7029",
    Model_Name_Short_M: "Crazyflight 6 W",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "NEW TOOLING",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/09/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 11:21 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:51 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 43,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL90",
    Article_Number_A: "HP7030",
    Model_Name_Short_M: "Crazyflight 6 Mid W ",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "MIXED COMPONENT",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 10:39 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:50 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 44,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL90",
    Article_Number_A: "HP7031",
    Model_Name_Short_M: "Crazyflight 6 Mid W ",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "MIXED COMPONENT",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 10:33 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:50 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 45,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL90",
    Article_Number_A: "HP7032",
    Model_Name_Short_M: "Crazyflight 6 Mid W ",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "MIXED COMPONENT",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 10:37 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:50 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 46,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL87",
    Article_Number_A: "HP7033",
    Model_Name_Short_M: "Crazyflight 6 M",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "TAKE DOWN",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 09:06 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:51 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 47,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL87",
    Article_Number_A: "HP7034",
    Model_Name_Short_M: "Crazyflight 6 M",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "TAKE DOWN",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 09:30 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:51 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 48,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "ONL89",
    Article_Number_A: "HP7037",
    Model_Name_Short_M: "Crazyflight 6 Mid M",
    Sports_Category_M: "INDOOR",
    Development_Type_A: "TAKE DOWN",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/08/2024",
    Marketing_Department_A: "BU TEAM SPORTS",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "10/30/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Zhang, Laura",
    Senior_Developer_A: "Roy.Williamson@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "CR2change",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "10/23/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "eac_hokim@emea.adsint.biz",
    Published_Milestone_Timestamp_A: "02/25/2025 04:15 PM GMT+07:00",
    Published_Milestone_A: "Final",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "02/24/2025 09:57 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "01/27/2025 07:49 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/16/2024",
    Image_Confidential_A: "No",
    Last_M: "22027",
  },
  {
    key: 49,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OPH33",
    Article_Number_A: "HP7186",
    Model_Name_Short_M: "SAMBA OG W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "11/12/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "12/03/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Geinzer, Carolin",
    Senior_Developer_A: "sven.liebold@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/26/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "03/01/2025 04:38 PM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "05/09/2025 08:10 PM GMT+07:00",
    Feasibility_Checked_Date_A: "10/30/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
  {
    key: 50,
    Season_M: "FW25",
    Creation_Workflow_M: "",
    Model_Number_M: "OPH68",
    Article_Number_A: "HP7215",
    Model_Name_Short_M: "GAZELLE INDOOR W",
    Sports_Category_M: "ORIGINALS",
    Development_Type_A: "NEW MATERIAL",
    Group_Name_A: "LYV_ALL",
    Development_Factory_M: "LYV",
    Digital_Scope_A: "VR1.0",
    Digital_Scope_Update_Date_A: "10/15/2024",
    Marketing_Department_A: "BU ORIGINALS FTW",
    Preview_Final_Rendering_available_Downstream_Date_A: "",
    Presell_Final_Rendering_available_Downstream_Date_A: "",
    SMS_Final_Rendering_available_Downstream_Date_A: "11/13/2024",
    MCS_Final_rendering_available_Downstream_Date_A: "",
    Article_Status_A: "IN RANGE",
    Carry_Over_Season_A: "",
    Consumer_Testing_A: "No",
    Image_Launch_Date_A: "",
    Developer_A: "Le, Tam",
    Senior_Developer_A: "david.nguyen@adidas.com",
    Drop_Date_A: "",
    Factory_3D_A: "LYV_ALL",
    Tags_A: "",
    Preview_Approval_Publish_Date_A: "",
    Presell_Approval_Publish_Date_A: "",
    SMS_Approval_Publish_Date_A: "11/06/2024",
    MCS_Approval_Publish_Date_A: "",
    Published_by_A: "",
    Published_Milestone_Timestamp_A: "",
    Published_Milestone_A: "Sell-In",
    Expected_Milestone_A: "SMS",
    HQ_Render_Status_Timestamp_A: "05/09/2025 11:12 AM GMT+07:00",
    HQ_Render_Status_A: "Completed",
    Design_Sketch_Latest_Update_A: "10/30/2024 05:03 PM GMT+07:00",
    Feasibility_Checked_Date_A: "11/01/2024",
    Image_Confidential_A: "No",
    Last_M: "41TUR",
  },
];
