import type { MaterialsDataType } from "./materials";
import type { DataType, MenuType, ModuleType, UsersDataType } from "./users";

export const data: DataType[] = [
  {
    key: "1",
    account: "00W001",
    name: "00W001 - YFY JUPITER (HKG)",
  },
  {
    key: "2",
    account: "00Z001",
    name: "00Z001 - APACHE FOOTWEAR VIETNAM (VNM)",
  },
  {
    key: "3",
    account: "1B9001",
    name: "1B9001 - PT GLOSTAR INDONESIA 1 (PGD IDN)",
  },
  {
    key: "4",
    account: "1BM001",
    name: "1BM001 - PT GLOSTAR INDONESIA 2 (PGS IDN)",
  },
  {
    key: "5",
    account: "1BM002",
    name: "1BM001 - PT GLOSTAR INDONESIA 2 (PGS IDN)",
  },
];

export const initialModuleData: ModuleType[] = [
  {
    key: "1",
    nameEn: "CI",
    nameVn: "CI",
    nameCn: "CI",
    status: "Active",
  },
  {
    key: "2",
    nameEn: "ESG",
    nameVn: "ESG",
    nameCn: "ESG",
    status: "Active",
  },
  {
    key: "3",
    nameEn: "GENERAL",
    nameVn: "GENERAL",
    nameCn: "GENERAL",
    status: "Active",
  },
  {
    key: "4",
    nameEn: "IT",
    nameVn: "IT",
    nameCn: "IT",
    status: "Active",
  },
  {
    key: "5",
    nameEn: "PLANNING",
    nameVn: "PLANNING",
    nameCn: "PLANNING",
    status: "Active",
  },
];

export const initialMenuData: MenuType[] = [
  {
    key: "1",
    module: "GENERAL",
    nameEn: "COLORS",
    nameVn: "COLORS",
    nameCn: "COLORS",
    status: "Active",
  },
  {
    key: "2",
    module: "ESG",
    nameEn: "MATERIALS",
    nameVn: "MATERIALS",
    nameCn: "MATERIALS",
    status: "Active",
  },
  {
    key: "3",
    module: "GENERAL",
    nameEn: "MATERIAL TEST REPORT",
    nameVn: "MATERIAL TEST REPORT",
    nameCn: "MATERIAL TEST REPORT",
    status: "Inactive",
  },
];

export const initialUsersData: UsersDataType[] = [
  {
    key: "1",
    userAccount: "1VW001",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW002",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW003",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW004",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW005",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW006",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW007",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW008",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW009",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW010",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW011",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW012",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW013",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW014",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW015",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW016",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW017",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW018",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW019",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW020",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW021",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW022",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW001",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW023",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW024",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW025",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW026",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW027",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW028",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW029",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW030",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW031",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW0032",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW033",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW034",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW035",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW036",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW037",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW038",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW039",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW040",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW041",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW042",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW043",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW044",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW045",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW046",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW047",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW048",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW049",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW050",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW051",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW052",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW053",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW054",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW055",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW056",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW057",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW058",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW059",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW060",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW061",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW062",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW063",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW064",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW065",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW066",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW067",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW068",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW069",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW070",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW071",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW072",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW073",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW074",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW075",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW076",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW077",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW078",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW079",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW080",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW081",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW082",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW083",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW084",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW085",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW086",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW087",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW088",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW089",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW090",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW091",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW092",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW093",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW094",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW095",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW096",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW097",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW098",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW099",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW100",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
  {
    key: "1",
    userAccount: "1VW101",
    // factory: "",
    levelPermission: "User",
    name: "1VW001 - KEY WAY (CHN)",
    // email: "",
    vendorCode: "1VW001",
    userCreated: "admin",
  },
];

export const initialMaterialsData: MaterialsDataType[] = [
  {
    ID: "98094",
    ID_Image: "556ed2e1-a07d-4db7-9aae-f219f51240aa",
    Unique_Price_ID: "a1d60a27-9d13-40ce-9468-e4491f27ff8d",
    Material_ID: "40090974",
    Vendor_Code: "Z33003",
    Supplier: "Z33003 (B) - DONG JIN (KOR)",
    Supplier_Material_ID: "40090974_Z33003",
    Supplier_Material_Name: "DJT 6867 MONO AMARE MESH P-CDP - WPN",
    Mtl_Supp_Lifecycle_State: "Limited Release",
    Material_Type_Level_1: "Textile",
    Composition: "57% PET-REC/43% PET-REC CD",
    Classification: "TEXTILE//FABRICS TEXTILE//KNITWEAR//Knitwear Mono Fiber",
    Material_Thickness: "z",
    Material_Thickness_UOM: "z",
    Comparison_UOM: "SQM",
    Price_Remark: "z",
    Skin_Size: "z",
    QC_Percent: "z",
    Leadtime: "21",
    Sample_Leadtime: "21",
    Min_Qty_Color: "100",
    Min_Qty_Sample: "0",
    Production_Location: "Indonesia, Korea, Vietnam",
    Terms_of_Delivery_per_T1_Country: "z",
    Valid_From_Price: "2025-09-01",
    Valid_To_Price: "2026-02-28",
    Price_Type: "Standard",
    Color_Code_Price: "z",
    Color_Price: "z",
    Treatment_Price: "z",
    Width_Price: "44",
    Width_Uom_Price: "INCH",
    Length_Price: "1",
    Length_Uom_Price: "YARD",
    Thickness_Price: "z",
    Thickness_Uom_Price: "z",
    Diameter_Inside_Price: "z",
    Diameter_Inside_Uom_Price: "z",
    Weight_Price: "z",
    Weight_Uom_Price: "z",
    Quantity_Price: "z",
    Quantity_Uom_Price: "z",
    Uom_String_Price: "44.00 INCH X 1.00 YARD",
    SS26_Final_Price_USD: "3.4",
    Comparison_Price_Price_USD: "3.327",
    Approved_As_Final_Price_Y_N_Price: "Y",
    UserID: "z",
    UserDate: "5/2/2025 11:12:00 AM",
    Season: "SS26",
    ID_MaterialImage: "10484",
    User_Account: "Z33003",
    File_Name: "",
  },
  {
    ID: "98095",
    ID_Image: "6f989b03-3608-4233-804c-7c0c8cb8c98a",
    Unique_Price_ID: "e72267a4-40ec-41d2-a3c0-6b6315811870",
    Material_ID: "40090974",
    Vendor_Code: "Z33003",
    Supplier: "Z33003 (B) - DONG JIN (KOR)",
    Supplier_Material_ID: "40090974_Z33003",
    Supplier_Material_Name: "DJT 6867 MONO AMARE MESH P-CDP - WPN",
    Mtl_Supp_Lifecycle_State: "Limited Release",
    Material_Type_Level_1: "Textile",
    Composition: "57% PET-REC/43% PET-REC CD",
    Classification: "TEXTILE//FABRICS TEXTILE//KNITWEAR//Knitwear Mono Fiber",
    Material_Thickness: "z",
    Material_Thickness_UOM: "z",
    Comparison_UOM: "SQM",
    Price_Remark: "z",
    Skin_Size: "z",
    QC_Percent: "z",
    Leadtime: "21",
    Sample_Leadtime: "21",
    Min_Qty_Color: "100",
    Min_Qty_Sample: "0",
    Production_Location: "Indonesia, Korea, Vietnam",
    Terms_of_Delivery_per_T1_Country: "z",
    Valid_From_Price: "2025-09-01",
    Valid_To_Price: "2026-02-28",
    Price_Type: "Color",
    Color_Code_Price: "z",
    Color_Price: "z",
    Treatment_Price: "z",
    Width_Price: "44",
    Width_Uom_Price: "INCH",
    Length_Price: "1",
    Length_Uom_Price: "YARD",
    Thickness_Price: "z",
    Thickness_Uom_Price: "z",
    Diameter_Inside_Price: "z",
    Diameter_Inside_Uom_Price: "z",
    Weight_Price: "z",
    Weight_Uom_Price: "z",
    Quantity_Price: "z",
    Quantity_Uom_Price: "z",
    Uom_String_Price: "44.00 INCH X 1.00 YARD",
    SS26_Final_Price_USD: "3.4",
    Comparison_Price_Price_USD: "3.327",
    Approved_As_Final_Price_Y_N_Price: "Y",
    UserID: "",
    UserDate: "5/2/2025 11:12:00 AM",
    Season: "SS26",
    ID_MaterialImage: "10485",
    User_Account: "Z33003",
    File_Name: "",
  },
];
